### ISSUE TITLE
Allow for configuring driver ags

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_flow#129]
The question came up on hows to customize [this list](https://github.com/luckyframework/lucky_flow/blob/master/src/lucky_flow/drivers/headless_chrome.cr#L3), but as of right now, you can't. Your options are to either "monkey patch", or just create a custom driver with these options (not horrible).

If you look at these options in headless chrome https://developers.google.com/web/updates/2017/04/headless-chrome we can see there's quite a few more options like `print-to-pdf` or `repl`... It would be cool if we could hook in to these so if you needed to add some extra options, it's configurable.

**Comment by matthewmcgarvey** [comment]
This has now been fixed. https://github.com/luckyframework/lucky_flow/blob/f9df0735e9ca1b580c47c8e6d5e96e474a1f1ffc/src/lucky_flow/selenium/chrome/driver.cr#L21-L29 you can define your own driver and specify the arguments you want
