### ISSUE TITLE
Add way to pause and continue flow

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_flow#27]
Calling this will cause the spec to pause after every interaction and ask the user to press enter to continue. This will make it so that you can look at the page in chrome, then decide to continue when you're ready

```crystal
LuckyFlow.debug do
  flow.click("@something")
end
```

Then when running tests

```
Pausing to debug... (press enter to continue, q to stop debugging)
```

**Comment by skojin** [comment]
Why block syntax? Now just LuckyFlow.debug or LuckyFlow.pause before call flow.click?
Quick insert single debug line is more easy then do block wrap.

**Comment by paulcsmith** [comment]
Could you provide an example of what you mean? I wrote this issue awhile ago so I’m not sure exactly how your example compares

**Comment by paulcsmith** [comment]
Oh I think I get it. Yeah I think that makes sense 👍
