### ISSUE TITLE
git tag mismatch with declared version

### ISSUE THREAD

**Issue by robacarp** [luckyframework/lucky_flow#40]
The most recent git tag is [v0.3.0](https://github.com/luckyframework/lucky_flow/releases/tag/v0.3.0) but the commit that points to is [updating the version of the shard to 0.2.1](https://github.com/luckyframework/lucky_flow/commit/9d5c3893a3e15836332a7ceaf8744f770248dbd3). 

The shard command takes this as a signal that it can't trust it fully, and every time a `shard build` command is issued it does a `shards update` first.

Hopefully fixed in the next release.

**Comment by paulcsmith** [comment]
Whoops! Thanks for pointing that out. Yeah I'll definitely make sure to bump and tag it correctly for the next release!

**Comment by paulcsmith** [comment]
Fixed in 0.4.0 :D
