### ISSUE TITLE
Consider clearing a field before updating it

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky_flow#45]
When filling out a field, LuckyFlow will only append to a field. I believe this is because it's using `send_keys` under the hood. This is fine on a field that is empty, but on a field that already has content it only appends to that field. You end up with fields like:

```crystal
First Name: EdwardPaul
```

Either we're some kind of very cool youtuber youth, or this is unexpected behavior.

One way to solve this (and the way I solved it in a [current project](https://github.com/edwardloveall/lucky_bits/pull/33/files#diff-8b5b06fa9c6b505c6308ec077146465f) is to hook into selenium's `clear` method to clear the field before sending keys to it.

Automatically clearing fields seems somehow a dangerous default, but maybe it's expected?

The other thing could be to parameterize the option:

```crystal
fill_form(ProfileForm, clear: true, first_name: "Paul")

element.fill("Paul", clear: true)
```

Seems okay, but also not super clean. I'll throw them both out here and maybe someone will come up with the obvious and clean solution that I'm not thinking of 😄

**Comment by edwardloveall** [comment]
To compound the issue a little, when you run the `be_on_page` expectation, it has fuzzy matching. `EdwardPaul` will match `Paul` so you often won't even notice the test is doing this.

**Comment by paulcsmith** [comment]
@edwardloveall I think clearing and then sending the keys would be the expected behavior. I think it’s a good start and we can tweak later if needed. 

Thanks for the super detailed issue. You’re an awesome writer
