### ISSUE TITLE
Investigate what it would take to automatically update chromedriver instead of bundling it

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/lucky_flow#54]
A different approach to #38

**Comment by paulcsmith** [comment]
Yeah. Maybe even just a bun script that would make this process easier. 

Btw Did you have to update chromedriver in LuckyFlow to work in your app or was the PR you just opened for  general maintenance?

**Comment by edwardloveall** [comment]
Half and half. I was getting warnings about chromedriver not being tested with chrome 75 (the latest version).
