### ISSUE TITLE
Can't compile flow when the app doesn't have a User

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky_flow#65]
Our app has a `Member`, but no `User` class, so when we try to add in flow, we get a compile error. We can alias this out, but it starts to make things a bit difficult with trying to coerce one type in to another that doesn't really respond the same way. 

https://github.com/luckyframework/lucky_flow/blob/master/src/lucky_flow.cr#L22

**Comment by smadeja** [comment]
Just bumped into this one too. I have no `User` class, so the flow won't compile. Would it be possible to drop this dependency?

**Comment by paulcsmith** [comment]
Yes definitely. We will work on this! In the meantime I'd suggest adding a fake User in your spec_helper

```
class User
  def id
    0
  end
end
```
