### ISSUE TITLE
Add #accept_alert and #dismiss_alert to LuckyFlow

### ISSUE THREAD

**Issue by bdtomlin** [luckyframework/lucky_flow#67]
It would be nice to have LuckyFlow#accept_alert and LuckyFlow#dismiss_alert. I think these are reasonably common for tests and it would be great to have them as well as some documentation.

It took a little time and some digging through LuckyFlow and the Selenium Webdriver to figure out if there was an available way to do this.

The implementation would be simple, just a method on LuckyFlow that calls `session.alert.accept` or `session.alert.dismiss`. The key is the documentation though.

**Comment by paulcsmith** [comment]
I think this would be great. I think adding an accept alert and dismiss alert methods that delegate to those selenium ones would be great!

Thanks for digging in and finding that
