### ISSUE TITLE
Use webdrivers.cr to auto-install the correct version

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_flow#74]
https://github.com/matthewmcgarvey/webdrivers.cr

See https://gitter.im/luckyframework/Lobby?at=5ea98b753d58de7a38e36686

> In lucky_flow, you'd update https://github.com/luckyframework/lucky_flow/blob/26ebd2e04b71880f554610e5df9fd7df75892c8b/src/lucky_flow/chromedriver.cr#L17 with Webdrivers::Chromedriver.install

We should probably make this configurable via Habitat. There may be people that do not want this, or environments where they want to use a preinstalled/vendored version

**Comment by matthewmcgarvey** [comment]
I'm not sure if it should go in this library our be included in the generated app.  I'm considering that capybara does not include the webdrivers gem, but it has to be added to the app.

The generated app would have LuckyFlow configured like:

```crystal
require "webdrivers"

LuckyFlow.configure do |settings|
  settings.chromedriver_path = Webdrivers::Chromedriver.install
end
```

**Comment by paulcsmith** [comment]
I think I'd prefer it to be in LuckyFlow so it "just works" out of the box. There are a lot of people that don't know about webdrivers  and there's lives would be a lot happier with it I think 😂

But I think some people may not want it so as long as we have an option to disable it/provide your own path then I think it is probably the best of both worlds.
