### ISSUE TITLE
Figure out how to run it headless

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_flow#8]
I tried and it errored out. Would love to make this an option though

**Comment by ianpurton** [comment]
I was trying to get this running on a C9 instance where chrome has to be headless.

I uncommented the chrome options line in server.cr
    
chromeOptions:            {args: ["no-sandbox", "headless", "disable-gpu"]},

And it started working for me.

**Comment by edwardloveall** [comment]
I think you fixed this here @paulcsmith https://github.com/luckyframework/lucky_flow/pull/37/files#diff-9e1f0a49893d0b82f86af7dc8766ce71

Closing this fore now. Feel free to reopen of course 🙂
