### ISSUE TITLE
Cannot call LuckyFlow.fill_form with a select field

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky_flow#85]
## Summary

The problem is really with this `Element#fill` method that calls `#clear` before calling `#send_keys`. https://github.com/luckyframework/lucky_flow/blob/b00a8d82df5fa1ba687be9715f8f8b9344d2b027/src/lucky_flow/element.cr#L27-L30

If the field is a select, calling `#clear` results in an invalid browser state. My guess is that it was meant only for `input` elements.

## Possible Solution

If it is true that only `input` elements should be cleared, the method could check the element's tag before calling `#clear`. The underlying selenium library has an `Element#tag_name` method that we could use.

I am current monkey patching `LuckyFlow::Element` like so:

```crystal
class LuckyFlow::Element
  def fill(value : String)
    clear if element.tag_name == "input"
    send_keys value
  end
end

```

**Comment by paulcsmith** [comment]
Yes that is the case regarding clear. If we didn't clear it, it would append values. I think your solution would work wodnerfully. Either that or use "overwrite the value" type method in Selenium that we could use for inputs *and* select, but I'm not sure that exists

Thanks for reporting!

**Comment by matthewmcgarvey** [comment]
I wonder if `fill` would be doing too much if it is expected to handle every type of input. I've been looking around at libraries I use and Cypress is a browser testing library for javascript and they have a `select` method that clicks open the dropdown, finds all the options, searches for the matching option and clicks that one https://github.com/cypress-io/cypress/blob/develop/packages/driver/src/cy/commands/actions/select.js

There is so much complexity we are avoiding by just doing `send_keys` but I'm not sure if that will work for a checkbox and it  definitely doesn't work for a multiselect. It also seems like it could be browser-specific but I haven't verified that.

**Comment by paulcsmith** [comment]
@matthewmcgarvey That is a great point...I'm not sure of the best solution 🤔My initial thought is that we add `select` and `check`, but I'd love it if we had a high-level method (whether that is `fill` or something else) that would intelligently do the right thing. Maybe it checks the element type and then uses `send_keys`, `check`, or `select` based on the input type? 

The main reason I'd like a higher-level method is so you can use `fill_form` and it "just works" and you don't need to worry about how it fills it out.

Does that make sense?

If so I think a plan forward would be:

* Add `select`
* Add `check` for radios/checkboxes
* Change `fill` to be smart and use `check`, `select` or `send_keys`
