### ISSUE TITLE
Get the value of an element with property rather than attribute

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky_flow#86]
`LuckyFlow::Element#value` is currently calling `attribute("value")` to get the value of the element. Source:
https://github.com/luckyframework/lucky_flow/blob/0afe110f00ff9edaa21300162516d27e79289a24/src/lucky_flow/element.cr#L16-L18

While this works with Chrome, it will not work if Firefox or any other browser driver is added. This is because `attribute` is meant to reference the static fields of an element. To get a dynamic field like value, we should be calling `property` instead. Reference this stackoverflow question for more information on the difference between attribute and property: https://stackoverflow.com/questions/6003819/what-is-the-difference-between-properties-and-attributes-in-html

It seems to be up to the browser whether or not attribute is updated for dynamic properties like value. Chrome is the only one I've seen so far to update it, but Safari and Firefox definitely do not.

The fix is simple and should "just work" :

```crystal
def value
  property("value")
end
```

**Comment by paulcsmith** [comment]
This sounds great to me. Thanks for the thorough issue and explanation
