### ISSUE TITLE
Refactor to support other browsers for testing

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky_flow#91]
The underlying selenium library being used has support for browsers other than Chrome. If we refactor a bit to pull the Chrome-specific code into its own class(es) we can easily add support for Firefox and Safari as well.

My thought is that since the Selenium library already uses the idea of Driver to represent a Browser (`Selenium::Chrome::Driver`), we can lift that terminology into this library. There would be a `LuckyFlow::Chrome::Driver` or something like that which does all of the Chrome configuration.

For right now we could hardcode the configuration to create the Chrome driver but eventually the configuration could be surfaced to switch.

**Comment by matthewmcgarvey** [comment]
All the Chrome specific stuff lives here at the moment: https://github.com/luckyframework/lucky_flow/blob/master/src/lucky_flow/server.cr

**Comment by watzon** [comment]
So I actually just posted in the gitter chat about this, but [Marionette](https://github.com/watzon/marionette) has just been updated to support all webdrivers across the borard with a very similar API to that of Selenium, but without the Java overhead. It would be really easy to integrate into Lucky Flow and would add support for about 8 different browsers.

**Comment by matthewmcgarvey** [comment]
@watzon Maybe it's because the libraries are named selenium and that means that there is java somewhere, but this library doesn't use java at all. Looking into Marionette, they're basically the same thing

**Comment by watzon** [comment]
Ahh yeah, I see Selenium and I think Selenium WebDriver which is written in Java.
