### ISSUE TITLE
Add ability to hover over an element

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/lucky_flow#97]
If any sort of hovering functionality needs to be tested, LuckyFlow doesn't have any API to facilitate it. Until https://github.com/matthewmcgarvey/selenium.cr/issues/11 was closed, there wasn't a good way to do it by dropping down to the selenium level either. Now that it is, we can provide an api for hovering over an element.

## Potential API

```crystal
flow = BaseFlow.new
flow.hover_over("@custom-select-menu")
```

**Comment by matthewmcgarvey** [comment]
@fernandes would you be interested in tackling this? Maybe you have a better idea of what the api should look like?

**Comment by fernandes** [comment]
hi @matthewmcgarvey , what if?

`el("@avatar-menu").hover(x: 0, y: 0)`

where x and y are the coordinates in the element we want to hover (if must be less than its width / height)

I'm trying to follow Lucky Flowk Element idea of finding and element and then having some methods like `value`, `fill`, `click`, `append`

wdyt?

**Comment by matthewmcgarvey** [comment]
Yea, I like that! I don't think coordinates are necessary though. There might be a time for that level of specificity, but I don't think LuckyFlow should handle it. In those scenarios users should drop down into the selenium level. `el(...).hover` is perfect 👍
